module.exports = {
  POWER_OUTAGE: "POWER_OUTAGE",
  FLOOD_RISK: "FLOOD_RISK",
  FUNDING_OPPORTUNITY: "FUNDING_OPPORTUNITY",
  CITIZEN_COMPLAINT: "CITIZEN_COMPLAINT",
  INFRASTRUCTURE_DAMAGE: "INFRASTRUCTURE_DAMAGE",
  BUDGET_RISK: "BUDGET_RISK",
  SENTIMENT_DROP: "SENTIMENT_DROP",
  UNKNOWN: "UNKNOWN"
};
